In [899]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df= pd.read_csv("C:\\Users\\LENOVO\\Desktop\\Development-jourey\\machinelearningworks\\algorithms\\superwised_machinelearning\\linear_regression_works\\carwork\\Car.csv.xls")

In [900]:
df.head()

,Name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Alto 800 LXI Opt,2023,410000,10000,Petrol,Individual,Manual,First Owner,19.03 kmpl,999 CC,71.01bhp,96Nm,5.0
1,Skoda Slavia 1.0 TSI Ambition,2023,1350000,10000,Petrol,Individual,Manual,First Owner,14.08 kmpl,1956 CC,167.67bhp,350nm,5.0
2,BMW 3 Series Gran Limousine 320Ld Luxury Line,2023,5800000,1000,Diesel,Dealer,Automatic,First Owner,18.15 kmpl,998 CC,118.35bhp,172Nm,5.0
3,MG ZS EV Exclusive,2023,2650000,10000,Electric,Dealer,Automatic,First Owner,32.52 kmpl,998 CC,58.33bhp,78Nm,5.0
4,Tata Punch Adventure,2023,715000,10000,Petrol,Individual,Manual,First Owner,12.15 kmpl,1451 CC,141bhp,250Nm,5.0

In [901]:
df.isnull().sum()

Name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [902]:
df[df.duplicated(keep=False)].head()

,Name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
24,Honda Civic ZX Diesel BSIV,2020,2125000,5500,Diesel,Dealer,Manual,First Owner,26.8 kmpl,1597 CC,118 bhp,300Nm@ 2000rpm,5.0
25,Honda Civic ZX Diesel BSIV,2020,2125000,5500,Diesel,Dealer,Manual,First Owner,26.8 kmpl,1597 CC,118 bhp,300Nm@ 2000rpm,5.0
34,Hyundai Xcent 1.2 VTVT SX,2020,524000,32000,Petrol,Individual,Manual,First Owner,20.14 kmpl,1197 CC,81.86 bhp,113.75nm@ 4000rpm,5.0
35,Hyundai Xcent 1.2 VTVT SX,2020,524000,32000,Petrol,Individual,Manual,First Owner,20.14 kmpl,1197 CC,81.86 bhp,113.75nm@ 4000rpm,5.0
36,Kia Seltos HTX Plus AT D,2020,1900000,5000,Diesel,Dealer,Automatic,First Owner,17.8 kmpl,1493 CC,113.4 bhp,250nm@ 1500-2750rpm,5.0

In [903]:
df.columns

Index(['Name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'torque',
       'seats'],
      dtype='object')

In [904]:
col= ['mileage', 'engine']
for i in col:
    df[i]=(df[i]).str.split(" ").str[0]

In [905]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8148 entries, 0 to 8147
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           8148 non-null   object
 1   year           8148 non-null   int64
 2   selling_price  8148 non-null   int64
 3   km_driven      8148 non-null   int64
 4   fuel           8148 non-null   object
 5   seller_type    8148 non-null   object
 6   transmission   8148 non-null   object
 7   owner          8148 non-null   object
 8   mileage        7927 non-null   object
 9   engine         7927 non-null   object
 10  max_power      7933 non-null   object
 11  torque         7926 non-null   object
 12  seats          7927 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 827.7+ KB

In [906]:
df.head()

,Name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Alto 800 LXI Opt,2023,410000,10000,Petrol,Individual,Manual,First Owner,19.03,999,71.01bhp,96Nm,5.0
1,Skoda Slavia 1.0 TSI Ambition,2023,1350000,10000,Petrol,Individual,Manual,First Owner,14.08,1956,167.67bhp,350nm,5.0
2,BMW 3 Series Gran Limousine 320Ld Luxury Line,2023,5800000,1000,Diesel,Dealer,Automatic,First Owner,18.15,998,118.35bhp,172Nm,5.0
3,MG ZS EV Exclusive,2023,2650000,10000,Electric,Dealer,Automatic,First Owner,32.52,998,58.33bhp,78Nm,5.0
4,Tata Punch Adventure,2023,715000,10000,Petrol,Individual,Manual,First Owner,12.15,1451,141bhp,250Nm,5.0

In [907]:
df["mileage"].value_counts()

mileage
18.9     225
19.7     173
18.6     164
21.1     158
17.0     133
        ...
14.5       1
12.12      1
16.09      1
23.3       1
17.97      1
Name: count, Length: 385, dtype: int64

In [908]:
df.head()

,Name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Alto 800 LXI Opt,2023,410000,10000,Petrol,Individual,Manual,First Owner,19.03,999,71.01bhp,96Nm,5.0
1,Skoda Slavia 1.0 TSI Ambition,2023,1350000,10000,Petrol,Individual,Manual,First Owner,14.08,1956,167.67bhp,350nm,5.0
2,BMW 3 Series Gran Limousine 320Ld Luxury Line,2023,5800000,1000,Diesel,Dealer,Automatic,First Owner,18.15,998,118.35bhp,172Nm,5.0
3,MG ZS EV Exclusive,2023,2650000,10000,Electric,Dealer,Automatic,First Owner,32.52,998,58.33bhp,78Nm,5.0
4,Tata Punch Adventure,2023,715000,10000,Petrol,Individual,Manual,First Owner,12.15,1451,141bhp,250Nm,5.0

In [909]:
df.columns

Index(['Name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'torque',
       'seats'],
      dtype='object')

In [910]:
col= [ 'mileage', 'engine',
       'seats']
for i in col:
    df[i]=(df[i]).astype(float)

In [911]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8148 entries, 0 to 8147
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           8148 non-null   object
 1   year           8148 non-null   int64
 2   selling_price  8148 non-null   int64
 3   km_driven      8148 non-null   int64
 4   fuel           8148 non-null   object
 5   seller_type    8148 non-null   object
 6   transmission   8148 non-null   object
 7   owner          8148 non-null   object
 8   mileage        7927 non-null   float64
 9   engine         7927 non-null   float64
 10  max_power      7933 non-null   object
 11  torque         7926 non-null   object
 12  seats          7927 non-null   float64
dtypes: float64(3), int64(3), object(7)
memory usage: 827.7+ KB

In [912]:
df["torque"]=df["torque"].str.split("Nm").str[0]
df["torque"]=df["torque"].str.split("nm").str[0]
df["torque"]=df["torque"].str.split("NM").str[0]
df["torque"]=df["torque"].str.split(" ").str[0]
df["torque"]=df["torque"].str.split("kgm").str[0]
df["torque"]=df["torque"].str.split("(").str[0]
df["torque"]=df["torque"].str.split("@").str[0]

In [913]:
df["max_power"].value_counts()

max_power
74 bhp       377
81.80 bhp    220
88.5 bhp     204
67 bhp       165
46.3 bhp     162
            ...
112.2 bhp      1
149.5 bhp      1
198.5 bhp      1
57 bhp         1
 bhp           1
Name: count, Length: 331, dtype: int64

In [914]:
df["torque"].value_counts()

torque
200     693
190     612
90      408
113     264
114     246
       ...
18        1
176       1
46.5      1
72.9      1
121       1
Name: count, Length: 245, dtype: int64

In [915]:
df["torque"]=df["torque"].astype(float)

In [916]:
df["max_power"]=df["max_power"].str.split("bhp").str[0]

df["max_power"]=df["max_power"].replace("",0)
df["max_power"]=df["max_power"].replace(" ",0)

In [917]:
df["max_power"]= df["max_power"].astype(float)

In [918]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8148 entries, 0 to 8147
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           8148 non-null   object
 1   year           8148 non-null   int64
 2   selling_price  8148 non-null   int64
 3   km_driven      8148 non-null   int64
 4   fuel           8148 non-null   object
 5   seller_type    8148 non-null   object
 6   transmission   8148 non-null   object
 7   owner          8148 non-null   object
 8   mileage        7927 non-null   float64
 9   engine         7927 non-null   float64
 10  max_power      7933 non-null   float64
 11  torque         7926 non-null   float64
 12  seats          7927 non-null   float64
dtypes: float64(5), int64(3), object(5)
memory usage: 827.7+ KB

In [919]:
df.isnull().sum()

Name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [920]:
df.head()

,Name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Alto 800 LXI Opt,2023,410000,10000,Petrol,Individual,Manual,First Owner,19.03,999.0,71.01,96.0,5.0
1,Skoda Slavia 1.0 TSI Ambition,2023,1350000,10000,Petrol,Individual,Manual,First Owner,14.08,1956.0,167.67,350.0,5.0
2,BMW 3 Series Gran Limousine 320Ld Luxury Line,2023,5800000,1000,Diesel,Dealer,Automatic,First Owner,18.15,998.0,118.35,172.0,5.0
3,MG ZS EV Exclusive,2023,2650000,10000,Electric,Dealer,Automatic,First Owner,32.52,998.0,58.33,78.0,5.0
4,Tata Punch Adventure,2023,715000,10000,Petrol,Individual,Manual,First Owner,12.15,1451.0,141.00,250.0,5.0

In [921]:
df["max_power"].value_counts()

max_power
74.00     377
81.80     222
88.50     222
67.00     165
46.30     162
         ...
116.90      1
138.08      1
163.20      1
198.50      1
57.00       1
Name: count, Length: 322, dtype: int64

In [922]:
df["brand"]=df["Name"].str.lstrip(" ").str.split(" ").str[0]

In [923]:
df[df["brand"]==""]

Empty DataFrame
Columns: [Name, year, selling_price, km_driven, fuel, seller_type, transmission, owner, mileage, engine, max_power, torque, seats, brand]
Index: []

In [924]:
df.columns

Index(['Name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'torque',
       'seats', 'brand'],
      dtype='object')

In [925]:
x=df[['brand','year', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'torque',
       'seats']]
y=df[[ 'selling_price',]]

In [926]:
x.head()

,brand,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti,2023,10000,Petrol,Individual,Manual,First Owner,19.03,999.0,71.01,96.0,5.0
1,Skoda,2023,10000,Petrol,Individual,Manual,First Owner,14.08,1956.0,167.67,350.0,5.0
2,BMW,2023,1000,Diesel,Dealer,Automatic,First Owner,18.15,998.0,118.35,172.0,5.0
3,MG,2023,10000,Electric,Dealer,Automatic,First Owner,32.52,998.0,58.33,78.0,5.0
4,Tata,2023,10000,Petrol,Individual,Manual,First Owner,12.15,1451.0,141.00,250.0,5.0

In [927]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(missing_values=np.nan,strategy="mean")
x[[ 'mileage', 'engine', 'max_power', 'torque',
       'seats']]= si.fit_transform(x[[ 'mileage', 'engine', 'max_power', 'torque',
       'seats']])

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_22788\2093234952.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[[ 'mileage', 'engine', 'max_power', 'torque',

In [928]:
x.isnull().sum()

brand           0
year            0
km_driven       0
fuel            0
seller_type     0
transmission    0
owner           0
mileage         0
engine          0
max_power       0
torque          0
seats           0
dtype: int64

In [929]:
#x["year"]=2026-x["year"]
df["brand"].value_counts()

brand
Maruti           2452
Hyundai          1419
Mahindra          774
Tata              735
Toyota            488
Honda             467
Ford              397
Renault           233
Chevrolet         230
Volkswagen        186
BMW               121
Skoda             106
Nissan             82
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
MG                  4
Kia                 4
Ambassador          4
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [930]:
x.head()

,brand,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti,2023,10000,Petrol,Individual,Manual,First Owner,19.03,999.0,71.01,96.0,5.0
1,Skoda,2023,10000,Petrol,Individual,Manual,First Owner,14.08,1956.0,167.67,350.0,5.0
2,BMW,2023,1000,Diesel,Dealer,Automatic,First Owner,18.15,998.0,118.35,172.0,5.0
3,MG,2023,10000,Electric,Dealer,Automatic,First Owner,32.52,998.0,58.33,78.0,5.0
4,Tata,2023,10000,Petrol,Individual,Manual,First Owner,12.15,1451.0,141.00,250.0,5.0

In [931]:
top_brands= df["brand"].value_counts().head(15).index

In [932]:
x["brand"]=df["brand"].apply(lambda x:x if x in top_brands else "others")

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_22788\1693111652.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["brand"]=df["brand"].apply(lambda x:x if x in top_brands else "others")

In [933]:
#encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer([("encoder",OneHotEncoder(),['brand', 'fuel', 'seller_type',
       'transmission', 'owner'])],remainder='passthrough')
x=pd.DataFrame(ct.fit_transform(x))

In [934]:
x.head()

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,2023.0,10000.0,19.03,999.0,71.01,96.0,5.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2023.0,10000.0,14.08,1956.0,167.67,350.0,5.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2023.0,1000.0,18.15,998.0,118.35,172.0,5.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2023.0,10000.0,32.52,998.0,58.33,78.0,5.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2023.0,10000.0,12.15,1451.0,141.00,250.0,5.0

In [935]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.2,random_state=42)

In [936]:
from sklearn.linear_model import LinearRegression
li=LinearRegression()
li.fit(xtrain,ytrain)
# print(f"slope {li.coef_}")
# print(f"c-intecept  {li.intercept_}")

LinearRegression()

In [937]:
ypred=li.predict(xtest)

In [938]:
from sklearn.metrics import r2_score
print(f"r2_score  {r2_score(ytest,ypred)}")

r2_score  0.7831638712345588

In [939]:
print("Train R2:", li.score(xtrain, ytrain))
print("Test R2:", li.score(xtest, ytest))

Train R2: 0.7968009798536724
Test R2: 0.7831638712345588

In [941]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor( random_state=42)
rf.fit(xtrain, ytrain)
ypred= rf.predict(xtest)
print(f"r2_score {r2_score(ytest,ypred)}")
print("Train R2:", rf.score(xtrain, ytrain))
print("Test R2:", rf.score(xtest, ytest))

c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

r2_score 0.9646576325609778
Train R2: 0.9931170986454821
Test R2: 0.9646576325609778