In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("C:\\Users\\LENOVO\\Desktop\\Development-jourey\\machinelearningworks\\Feature_engineering\\intro\\student_data.csv.xls")

In [5]:
copy=df.copy()

In [6]:
copy.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,1,3,16,13,0,2,0,0,0,0,3.158425,1
1,1002,18,1,2,0,17,28,0,2,1,1,1,0,2.794655,2
2,1003,15,1,0,1,13,18,1,4,0,0,0,1,3.774847,0
3,1004,17,1,0,3,6,4,0,3,1,0,0,0,3.040574,1
4,1005,17,0,1,2,6,20,0,4,0,0,0,0,3.382310,1

In [7]:
copy.isnull().sum()

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [8]:
copy.columns

Index(['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation',
       'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport',
       'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA',
       'GradeClass'],
      dtype='object')

In [9]:
copy.shape

(5000, 15)

In [10]:
copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          5000 non-null   int64
 1   Age                5000 non-null   int64
 2   Gender             5000 non-null   int64
 3   Ethnicity          5000 non-null   int64
 4   ParentalEducation  5000 non-null   int64
 5   StudyTimeWeekly    5000 non-null   int64
 6   Absences           5000 non-null   int64
 7   Tutoring           5000 non-null   int64
 8   ParentalSupport    5000 non-null   int64
 9   Extracurricular    5000 non-null   int64
 10  Sports             5000 non-null   int64
 11  Music              5000 non-null   int64
 12  Volunteering       5000 non-null   int64
 13  GPA                5000 non-null   float64
 14  GradeClass         5000 non-null   int64
dtypes: float64(1), int64(14)
memory usage: 586.1 KB

In [11]:
copy["GPA"]=copy["GPA"].astype("int")

In [13]:
copy.dtypes

StudentID            int64
Age                  int64
Gender               int64
Ethnicity            int64
ParentalEducation    int64
StudyTimeWeekly      int64
Absences             int64
Tutoring             int64
ParentalSupport      int64
Extracurricular      int64
Sports               int64
Music                int64
Volunteering         int64
GPA                  int64
GradeClass           int64
dtype: object

In [14]:
copy.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,1,3,16,13,0,2,0,0,0,0,3,1
1,1002,18,1,2,0,17,28,0,2,1,1,1,0,2,2
2,1003,15,1,0,1,13,18,1,4,0,0,0,1,3,0
3,1004,17,1,0,3,6,4,0,3,1,0,0,0,3,1
4,1005,17,0,1,2,6,20,0,4,0,0,0,0,3,1

In [15]:
copy.drop(columns="StudentID",inplace=True)

In [16]:
X= copy.iloc[:,:-1]
Y = copy.iloc[:,-1]

In [17]:
X

,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA
0,17,1,1,3,16,13,0,2,0,0,0,0,3
1,18,1,2,0,17,28,0,2,1,1,1,0,2
2,15,1,0,1,13,18,1,4,0,0,0,1,3
3,17,1,0,3,6,4,0,3,1,0,0,0,3
4,17,0,1,2,6,20,0,4,0,0,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,15,0,3,2,12,22,0,2,0,1,1,0,4
4996,16,0,1,2,1,2,0,2,0,1,0,0,2
4997,17,1,1,3,18,18,1,0,1,0,0,1,4
4998,16,0,2,2,15,0,0,2,1,1,1,0,4
4999,18,1,2,4,4,23,0,0,1,0,0,1,2

In [18]:
Y

0       1
1       2
2       0
3       1
4       1
       ..
4995    0
4996    2
4997    0
4998    0
4999    3
Name: GradeClass, Length: 5000, dtype: int64

In [ ]:
! pip install scikit_learn

^C

Requirement already satisfied: scikit_learn in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from scikit_learn) (2.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from scikit_learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from scikit_learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from scikit_learn) (3.6.0)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [21]:
! pip list

Package                 Version
----------------------- -----------
asgiref                 3.10.0
asttokens               3.0.1
certifi                 2025.8.3
charset-normalizer      3.4.3
colorama                0.4.6
comm                    0.2.3
contourpy               1.3.3
cycler                  0.12.1
debugpy                 1.8.19
decorator               5.2.1
distlib                 0.4.0
Django                  5.2.7
docutils                0.22
et_xmlfile              2.0.0
executing               2.2.1
filelock                3.20.3
filetype                1.2.0
fonttools               4.61.1
idna                    3.10
ipykernel               7.1.0
ipython                 9.9.0
ipython_pygments_lexers 1.1.1
jedi                    0.19.2
joblib                  1.5.3
jupyter_client          8.8.0
jupyter_core            5.9.1
Kivy                    2.3.1
kivy_deps.angle         0.4.0
kivy_deps.glew          0.3.1
kivy_deps.sdl2          0.8.0
Kivy-Garden             0.1.5
kiwisolver              1.4.9
matplotlib              3.10.8
matplotlib-inline       0.2.1
mysql-connector-python  9.5.0
nest-asyncio            1.6.0
numpy                   2.3.2
openpyxl                3.1.5
packaging               25.0
pandas                  2.3.1
parso                   0.8.5
pillow                  12.1.0
pip                     25.1.1
platformdirs            4.5.1
prompt_toolkit          3.0.52
psutil                  7.2.1
pure_eval               0.2.3
Pygments                2.19.2
pyparsing               3.3.2
pypiwin32               223
python-dateutil         2.9.0.post0
pytz                    2025.2
pywin32                 311
pyzmq                   27.1.0
requests                2.32.4
scikit-learn            1.8.0
scipy                   1.17.0
seaborn                 0.13.2
six                     1.17.0
sqlparse                0.5.3
stack-data              0.6.3
threadpoolctl           3.6.0
tornado                 6.5.4
traitlets               5.14.3
tzdata                  2025.2
urllib3                 2.5.0
virtualenv              20.36.1
wcwidth                 0.2.14

In [22]:
! pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
from sklearn.preprocessing import MinMaxScaler

In [25]:
scaler = MinMaxScaler()

In [27]:
Xscaled=scaler.fit_transform(X)
Xscaled

array([[0.66666667, 1.        , 0.33333333, ..., 0.        , 0.        ,
        0.5       ],
       [1.        , 1.        , 0.66666667, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 1.        ,
        0.5       ],
       ...,
       [0.66666667, 1.        , 0.33333333, ..., 0.        , 1.        ,
        1.        ],
       [0.33333333, 0.        , 0.66666667, ..., 1.        , 0.        ,
        1.        ],
       [1.        , 1.        , 0.66666667, ..., 0.        , 1.        ,
        0.        ]], shape=(5000, 13))

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train,X_test,Y_train,Y_test = train_test_split(Xscaled,Y,test_size=0.2)

In [30]:
X_train

array([[0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        1.        ],
       [1.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.5       ],
       [0.33333333, 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [1.        , 1.        , 0.        , ..., 1.        , 0.        ,
        0.5       ],
       [0.66666667, 1.        , 0.66666667, ..., 1.        , 0.        ,
        1.        ],
       [0.33333333, 1.        , 0.66666667, ..., 0.        , 0.        ,
        0.5       ]], shape=(4000, 13))

In [31]:
X_test

array([[1.        , 0.        , 0.33333333, ..., 1.        , 0.        ,
        1.        ],
       [0.        , 1.        , 1.        , ..., 0.        , 1.        ,
        0.5       ],
       [0.33333333, 1.        , 1.        , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.        , 1.        , 0.66666667, ..., 0.        , 1.        ,
        0.5       ],
       [0.33333333, 1.        , 0.        , ..., 0.        , 0.        ,
        0.5       ],
       [0.        , 1.        , 0.66666667, ..., 0.        , 0.        ,
        1.        ]], shape=(1000, 13))