In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_excel("C:\\Users\\LENOVO\\Desktop\\Development-jourey\\machinelearningworks\\seaborn_works\\flight\\Data_Train.xlsx")
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [3]:
! pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [5]:
df.shape

(10683, 11)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [7]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [8]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [9]:
df["Total_Stops"].value_counts()

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
4 stops        1
Name: count, dtype: int64

In [10]:
df["day"]=df["Date_of_Journey"].str.split("/").str[0]
df["month"]=df["Date_of_Journey"].str.split("/").str[1]
df["year"]=df["Date_of_Journey"].str.split("/").str[2]

In [11]:
df.drop(columns="Date_of_Journey",inplace=True)

In [12]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Arrival_Time',
       'Duration', 'Total_Stops', 'Additional_Info', 'Price', 'day', 'month',
       'year'],
      dtype='object')

In [13]:
df["day"]=df["day"].astype("int")
df["month"]=df["month"].astype("int")
df["year"]=df["year"].astype("int")

In [14]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019

In [15]:
df["depature_hour"]=df["Dep_Time"].str.split(":").str[0]
df["depature_minute"]=df["Dep_Time"].str.split(":").str[1]

In [16]:
df.head(1)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year,depature_hour,depature_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,22,20

In [17]:
df.drop(columns="Dep_Time",inplace=True)

In [18]:
df["Total_Stops"]=df["Total_Stops"].str.split(" ").str[0]

In [19]:
df["Arrival_Time"]=df["Arrival_Time"].str.split(" ").str[0]

In [20]:
df["arrival_hour"]=df["Arrival_Time"].str.split(":").str[0]
df["arrival_min"]=df["Arrival_Time"].str.split(":").str[1]

In [21]:
df.drop(columns="Arrival_Time",inplace=True)

In [22]:
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,day,month,year,depature_hour,depature_minute,arrival_hour,arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,22,20,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2,No info,7662,1,5,2019,05,50,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2,No info,13882,9,6,2019,09,25,04,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1,No info,6218,12,5,2019,18,05,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1,No info,13302,1,3,2019,16,50,21,35

In [23]:
#df["Total_Stops"]=df["Total_Stops"].map({"non_stop":0})

In [24]:
df["Total_Stops"].value_counts()

Total_Stops
1           5625
non-stop    3491
2           1520
3             45
4              1
Name: count, dtype: int64

In [25]:
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,day,month,year,depature_hour,depature_minute,arrival_hour,arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,22,20,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2,No info,7662,1,5,2019,05,50,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2,No info,13882,9,6,2019,09,25,04,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1,No info,6218,12,5,2019,18,05,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1,No info,13302,1,3,2019,16,50,21,35

In [26]:
# .replace() leaves values alone if they aren't in the dictionary
df["Total_Stops"] = df["Total_Stops"].replace({"non-stop": 0})

In [27]:
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,day,month,year,depature_hour,depature_minute,arrival_hour,arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0,No info,3897,24,3,2019,22,20,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2,No info,7662,1,5,2019,05,50,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2,No info,13882,9,6,2019,09,25,04,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1,No info,6218,12,5,2019,18,05,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1,No info,13302,1,3,2019,16,50,21,35

In [28]:
df["Total_Stops"].fillna(df["Total_Stops"].mode(),inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_16704\1873622403.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Total_Stops"].fillna(df["Total_Stops"].mode(),inplace=True)

In [29]:
df["duration_hour"]=df["Duration"].str.extract(r'(\d+)h')

df["Duration_min"]=df["Duration"].str.extract(r'(\d+)m')

In [30]:
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,day,month,year,depature_hour,depature_minute,arrival_hour,arrival_min,duration_hour,Duration_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0,No info,3897,24,3,2019,22,20,01,10,2,50
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2,No info,7662,1,5,2019,05,50,13,15,7,25
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2,No info,13882,9,6,2019,09,25,04,25,19,NaN
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1,No info,6218,12,5,2019,18,05,23,30,5,25
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1,No info,13302,1,3,2019,16,50,21,35,4,45

In [31]:
df["Duration_min"].fillna(0,inplace=True)
df["duration_hour"].fillna(0,inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_16704\1080110198.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Duration_min"].fillna(0,inplace=True)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_16704\1080110198.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["duration_hour"].fillna(0,inplace=True)

In [32]:
df.drop(columns="Duration",inplace=True)

In [33]:
df["total_duration_in_minute"]=df["duration_hour"].astype("int")*60+df["Duration_min"].astype("int")
df["total_duration_in_hr"]=df["total_duration_in_minute"].astype("int")/60

In [34]:
df["duration_hour"]=df["duration_hour"].astype("int")
df["total_duration_in_hr"]=round(df["total_duration_in_hr"],2)

In [35]:
df.head()

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,day,month,year,depature_hour,depature_minute,arrival_hour,arrival_min,duration_hour,Duration_min,total_duration_in_minute,total_duration_in_hr
0,IndiGo,Banglore,New Delhi,BLR → DEL,0,No info,3897,24,3,2019,22,20,01,10,2,50,170,2.83
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662,1,5,2019,05,50,13,15,7,25,445,7.42
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2,No info,13882,9,6,2019,09,25,04,25,19,0,1140,19.00
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1,No info,6218,12,5,2019,18,05,23,30,5,25,325,5.42
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1,No info,13302,1,3,2019,16,50,21,35,4,45,285,4.75

In [36]:
df.tail()

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,day,month,year,depature_hour,depature_minute,arrival_hour,arrival_min,duration_hour,Duration_min,total_duration_in_minute,total_duration_in_hr
10678,Air Asia,Kolkata,Banglore,CCU → BLR,0,No info,4107,9,4,2019,19,55,22,25,2,30,150,2.50
10679,Air India,Kolkata,Banglore,CCU → BLR,0,No info,4145,27,4,2019,20,45,23,20,2,35,155,2.58
10680,Jet Airways,Banglore,Delhi,BLR → DEL,0,No info,7229,27,4,2019,08,20,11,20,3,0,180,3.00
10681,Vistara,Banglore,New Delhi,BLR → DEL,0,No info,12648,1,3,2019,11,30,14,10,2,40,160,2.67
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2,No info,11753,9,5,2019,10,55,19,15,8,20,500,8.33

In [37]:
df[df["total_duration_in_minute"]==df["total_duration_in_minute"].max()]

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,day,month,year,depature_hour,depature_minute,arrival_hour,arrival_min,duration_hour,Duration_min,total_duration_in_minute,total_duration_in_hr
10456,Jet Airways,Delhi,Cochin,DEL → AMD → BOM → COK,2,No info,20694,6,3,2019,19,10,18,50,47,40,2860,47.67

In [38]:
df.head()

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,day,month,year,depature_hour,depature_minute,arrival_hour,arrival_min,duration_hour,Duration_min,total_duration_in_minute,total_duration_in_hr
0,IndiGo,Banglore,New Delhi,BLR → DEL,0,No info,3897,24,3,2019,22,20,01,10,2,50,170,2.83
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662,1,5,2019,05,50,13,15,7,25,445,7.42
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2,No info,13882,9,6,2019,09,25,04,25,19,0,1140,19.00
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1,No info,6218,12,5,2019,18,05,23,30,5,25,325,5.42
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1,No info,13302,1,3,2019,16,50,21,35,4,45,285,4.75

In [39]:
df.isnull().sum()

Airline                     0
Source                      0
Destination                 0
Route                       1
Total_Stops                 1
Additional_Info             0
Price                       0
day                         0
month                       0
year                        0
depature_hour               0
depature_minute             0
arrival_hour                0
arrival_min                 0
duration_hour               0
Duration_min                0
total_duration_in_minute    0
total_duration_in_hr        0
dtype: int64

In [40]:
df[df["Total_Stops"].isnull()]

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,day,month,year,depature_hour,depature_minute,arrival_hour,arrival_min,duration_hour,Duration_min,total_duration_in_minute,total_duration_in_hr
9039,Air India,Delhi,Cochin,NaN,NaN,No info,7480,6,5,2019,09,45,09,25,23,40,1420,23.67

In [41]:
df.groupby("Total_Stops")["total_duration_in_hr"].mean()

Total_Stops
0     2.500925
1    13.032229
2    20.559039
3    25.791778
4    29.500000
Name: total_duration_in_hr, dtype: float64

In [ ]:

selection =np.where(df["total_duration_in_hr"]>0     2.500925
1    13.032229
2    20.559039
3    25.791778
4    29.500000)